name: cd pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    uses: ./.github/workflows/ci.yml
    permissions:
        contents: read
        checks: write
   
  deploy:
     needs: [build]
     runs-on: self-hosted
     steps:
       - name: docker login
         run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       - name: pull docker image
         run: sudo docker pull abhishekrockzz78/ec2deploy:latest
       - name: delete old docker container
         run: sudo docker rm -f ec2deploy-container || true
       - name: Run docker container
         run: sudo docker run -d -p 8080:8080 --name ec2deploy-container abhishekrockzz78/ec2deploy
     
     
